/* Static paper data and recorded excerpts are generated by build_site_assets.py. */
"use strict";
const data = window.DUPLEX_DATA;
const $ = (selector) => document.querySelector(selector);
let exampleId = "yield";
let modelId = Object.keys(data.examples[exampleId].models)[0];
const audio = $("#demo-audio");

function element(tag, className, text) {
  const node = document.createElement(tag);
  if (className) node.className = className;
  if (text !== undefined) node.textContent = text;
  return node;
}

function renderAuthors() {
  for (const author of data.authors) {
    const span = element("span", "", author.name);
    const marks = [...author.affiliations];
    if (author.equal) marks.push("*");
    if (author.corresponding) marks.push("†");
    span.append(element("sup", "", marks.join(",")));
    $("#authors").append(span);
  }
  for (const [number, name] of Object.entries(data.institutions)) {
    const span = element("span");
    span.append(element("sup", "", number), document.createTextNode(name));
    $("#institutions").append(span);
  }
}

function drawWave(selector, bins, color) {
  const target = $(selector);
  target.replaceChildren();
  const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
  svg.setAttribute("viewBox", `0 0 ${bins.length * 2} 54`);
  svg.setAttribute("preserveAspectRatio", "none");
  const path = document.createElementNS(svg.namespaceURI, "path");
  path.setAttribute("d", bins.map((peak, index) => {
    const height = Math.max(.25, peak * 22);
    return `M${index * 2} ${27 - height}v${2 * height}`;
  }).join(""));
  path.setAttribute("stroke", color);
  path.setAttribute("stroke-width", "1.3");
  svg.append(path);
  target.append(svg, element("div", "elapsed"), element("div", "playhead"));
}

function utterance(turn) {
  const item = element("div", "utterance");
  item.append(element("span", "speaker", turn.speaker), element("p", "", turn.text));
  if (turn.start !== undefined) {
    item.dataset.start = turn.start;
    item.dataset.end = turn.end;
  }
  return item;
}

function activeRecording() {
  return data.examples[exampleId].models[modelId];
}

function renderExample() {
  audio.pause();
  const example = data.examples[exampleId];
  const clip = activeRecording();
  const options = Object.entries(example.models).map(([id, recording]) => {
    const option = element("option", "", recording.displayName);
    option.value = id;
    option.selected = id === modelId;
    return option;
  });
  $("#model-select").replaceChildren(...options);
  $("#audio-error").hidden = true;
  audio.src = clip.audio;
  audio.load();
  $("#audio-download").href = clip.audio;
  $("#scenario-label").textContent = `${example.side} · SCENARIO ${example.scenario.split("_").at(-1)} · TURN ${example.turn}`;
  $("#demo-title").textContent = example.title;
  $("#demo-description").textContent = example.description;
  $("#duration-label").textContent = `${clip.duration.toFixed(1)} s`;
  $("#human-transcript").replaceChildren(...clip.transcript.map(utterance));
  $("#history-transcript").replaceChildren(...example.history.map(utterance));
  $("#model-transcript-label").textContent = clip.transcriptScope.toUpperCase();
  $("#model-transcript").textContent = clip.modelTranscript || "No transcribed speech.";
  const gold = $("#gold-answer");
  gold.hidden = !example.goldAnswer;
  gold.replaceChildren();
  if (example.goldAnswer) gold.append(element("strong", "", "Reference answer"), document.createTextNode(example.goldAnswer));
  $("#verdict").textContent = clip.verdict;
  $("#verdict").className = `verdict${clip.passed === false ? " fail" : clip.passed === null ? " neutral" : ""}`;
  $("#verdict-note").textContent = clip.note;
  drawWave("#human-wave", clip.humanWave, "#397360");
  drawWave("#model-wave", clip.modelWave, "#bd785c");
  $("#timeline-markers").replaceChildren();
  $("#seek-buttons").replaceChildren();
  for (const marker of clip.markers) {
    if (marker.time <= clip.duration) {
      const tick = element("span", "time-marker", `${marker.time.toFixed(1)}s`);
      tick.dataset.marker = marker.id;
      tick.title = marker.label;
      tick.style.left = `${marker.time / clip.duration * 100}%`;
      $("#timeline-markers").append(tick);
      const button = element("button", "", `${marker.label} ↗`);
      button.type = "button";
      button.dataset.seek = marker.id;
      button.addEventListener("click", () => {
        if (audio.readyState >= 1) {
          audio.currentTime = marker.time;
          updateTime();
        }
      });
      $("#seek-buttons").append(button);
    }
  }
  document.querySelectorAll("[data-example]").forEach(button => {
    button.setAttribute("aria-pressed", String(button.dataset.example === exampleId));
  });
  updateTime();
}

function updateTime() {
  const duration = activeRecording().duration;
  const progress = Math.min(100, Math.max(0, audio.currentTime / duration * 100));
  document.querySelectorAll(".playhead").forEach(node => { node.style.left = `${progress}%`; });
  document.querySelectorAll(".elapsed").forEach(node => { node.style.width = `${progress}%`; });
  document.querySelectorAll("#human-transcript .utterance").forEach(node => {
    node.classList.toggle("active", audio.currentTime >= Number(node.dataset.start) && audio.currentTime < Number(node.dataset.end));
  });
}

function renderResults(side) {
  const rows = data.results.filter(row => row.side === side);
  const best = [0, 1, 2, 3].map(i => Math.max(...rows.map(row => row.values[i] === null ? -1 : row.values[i])));
  const body = $("#results-body");
  body.replaceChildren();
  for (const result of rows) {
    const tr = element("tr");
    tr.dataset.model = result.model;
    const model = element("th", "", data.models[result.model]);
    model.scope = "row";
    tr.append(model);
    for (const [index, value] of result.values.entries()) {
      const td = element("td");
      const formatted = value === null ? "n/a" : (value * 100).toFixed(2);
      td.append(element(index < 4 && value === best[index] ? "strong" : "span", "", formatted));
      if (index === 3) td.append(element("small", "", `n = ${result.yieldCount.toLocaleString("en-US")}`));
      tr.append(td);
    }
    body.append(tr);
  }
  $("#result-side-note").textContent = side === "src"
    ? "SRC: the 2,000 original scenarios. Each contains an explicit or implicit request; FLIP reverses its addressing form. SRC is not an explicit-only subset."
    : "FLIP: the 2,000 paired counterparts, with each request’s addressing form reversed. Both SRC and FLIP contain explicit and implicit requests.";
  document.querySelectorAll("[data-side]").forEach(button => {
    button.setAttribute("aria-pressed", String(button.dataset.side === side));
  });
}

document.querySelectorAll("[data-example]").forEach(button => {
  button.addEventListener("click", () => {
    exampleId = button.dataset.example;
    modelId = Object.keys(data.examples[exampleId].models)[0];
    renderExample();
  });
});
$("#model-select").addEventListener("change", event => { modelId = event.target.value; renderExample(); });
document.querySelectorAll("[data-side]").forEach(button => {
  button.addEventListener("click", () => renderResults(button.dataset.side));
});
audio.addEventListener("timeupdate", updateTime);
audio.addEventListener("error", () => { $("#audio-error").hidden = false; });
$("#copy-citation").addEventListener("click", async () => {
  try {
    if (!navigator.clipboard) throw new Error("Clipboard unavailable");
    await navigator.clipboard.writeText($("#bibtex").textContent);
    $("#copy-status").textContent = "Copied";
  } catch {
    const range = document.createRange();
    range.selectNodeContents($("#bibtex"));
    const selection = window.getSelection();
    selection.removeAllRanges();
    selection.addRange(range);
    $("#copy-status").textContent = "Selected — press Ctrl/Cmd+C";
  }
});
renderAuthors();
renderExample();
renderResults("src");
